name: Docs CI

on: [push, pull_request]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v9
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --no-progress docs/**/*.md